apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-logs
  labels:
    project: zhongshi
    type: log
    env: dev
spec:
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/nfs/k8s/logs/dev"
    server: 192.168.118.74

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-logs
  namespace: dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      project: zhongshi
      type: log
      env: dev
