apiVersion: v1
kind: PersistentVolume
metadata:
  name: uat-logs
  labels:
    project: zhongshi
    type: log
    env: uat
spec:
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/nfs/k8s/logs/uat"
    server: 192.168.118.74

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uat-logs
  namespace: uat
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      project: zhongshi
      type: log
      env: uat
