apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-logs
  labels:
    project: zhongshi
    type: log
    user: filebeat
spec:
  storageClassName: nfs-client
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/nfs/k8s/logs"
    server: 192.168.118.74

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-logs
  namespace: common
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      project: zhongshi
      type: log
      user: filebeat
